package customErrors

const (
	VALIDATION_EMAIL_REQUIRED            = "VALIDATION_EMAIL_REQUIRED"
	VALIDATION_PASSWORD_REQUIRED         = "VALIDATION_PASSWORD_REQUIRED"
	VALIDATION_PASSWORD_TOO_SHORT        = "VALIDATION_PASSWORD_TOO_SHORT"
	VALIDATION_FIRST_NAME_REQUIRED       = "VALIDATION_FIRST_NAME_REQUIRED"
	VALIDATION_LAST_NAME_REQUIRED        = "VALIDATION_LAST_NAME_REQUIRED"
	VALIDATION_PHONE_REQUIRED            = "VALIDATION_PHONE_REQUIRED"
	VALIDATION_FAILED                    = "VALIDATION_FAILED"
	VALIDATION_FIELD_MISSING             = "VALIDATION_FIELD_MISSING"
	VALIDATION_INVALID_FORMAT            = "VALIDATION_INVALID_FORMAT"
	VALIDATION_OUT_OF_RANGE              = "VALIDATION_OUT_OF_RANGE"
	VALIDATION_EMAIL_INVALID             = "VALIDATION_EMAIL_INVALID"
	VALIDATION_PASSWORD_WEAK             = "VALIDATION_PASSWORD_WEAK"
	VALIDATION_DUPLICATE                 = "VALIDATION_DUPLICATE"
	VALIDATION_EMAIL_DUPLICATE           = "VALIDATION_EMAIL_DUPLICATE"
	VALIDATION_PASSWORD_MISMATCH         = "VALIDATION_PASSWORD_MISMATCH"
	VALIDATION_CONFIRM_PASSWORD_REQUIRED = "VALIDATION_CONFIRM_PASSWORD_REQUIRED"
	VALIDATION_REFRESH_TOKEN_REQUIRED    = "VALIDATION_REFRESH_TOKEN_REQUIRED"
)
